# .github/workflows/deploy.yml

name: Build and deploy Node.js app to Azure Web App - unlock-app-ia

on:
  push:
    branches:
      - deploy_azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # Usar una versión LTS (Long-Term Support) es más seguro para producción
          node-version: '20.x'

      - name: Install dependencies & build backend
        # 1. RUTA CORREGIDA: Apuntamos a la carpeta correcta del backend
        working-directory: ./unlock-ai-app/backend
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # 2. ARTEFACTO CORREGIDO: Empaquetamos toda la carpeta de la app
          # Esto incluye /frontend y /backend (con el /dist ya creado)
          path: ./unlock-ai-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # Descargamos el contenido del artefacto a la raíz del espacio de trabajo
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FE5D1EB66B84462FA0EAA1D33E97B102 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_516AEBF0C40A4BCA82B0015115C89269 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB7B47FB5D8844BB8DC3D65CF2F8936E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unlock-app-ia'
          slot-name: 'Production'
          # 3. PAQUETE CORRECTO: "package" ahora apunta a la raíz que contiene
          # la estructura completa (frontend/ y backend/) que Azure necesita.
          package: .
